create table if not exists public."User" (
  id serial primary key,
  email varchar(64),
  password varchar(64)
);

create unique index if not exists "User_email_unique"
on public."User" using btree (email)
where email is not null;

create index if not exists words_book_id_word_rank_idx
on public.words using btree (book_id, word_rank);

create index if not exists words_book_id_head_word_idx
on public.words using btree (book_id, head_word);

create table if not exists public.user_book_progress (
  id bigint generated by default as identity not null,
  user_id integer not null,
  book_id text not null,
  current_word_id bigint null,
  current_word_rank integer not null default 0,
  learned_count integer not null default 0,
  total_words integer not null default 0,
  status text not null default 'not_started',
  last_opened_at timestamp with time zone null,
  last_studied_at timestamp with time zone null,
  completed_at timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint user_book_progress_pkey primary key (id),
  constraint user_book_progress_user_fk foreign key (user_id)
    references public."User" (id) on delete cascade,
  constraint user_book_progress_book_fk foreign key (book_id)
    references public.books (book_id) on delete cascade,
  constraint user_book_progress_current_word_fk foreign key (current_word_id)
    references public.words (id) on delete set null,
  constraint user_book_progress_user_book_unique unique (user_id, book_id),
  constraint user_book_progress_status_check check (
    status in ('not_started', 'learning', 'completed')
  ),
  constraint user_book_progress_counts_check check (
    learned_count >= 0 and total_words >= 0 and learned_count <= total_words
  ),
  constraint user_book_progress_rank_check check (current_word_rank >= 0)
);

create index if not exists user_book_progress_user_recent_idx
on public.user_book_progress using btree (
  user_id,
  last_studied_at desc nulls last,
  last_opened_at desc nulls last,
  updated_at desc
);

create index if not exists user_book_progress_book_idx
on public.user_book_progress using btree (book_id);

create table if not exists public.user_word_study_records (
  id bigint generated by default as identity not null,
  user_id integer not null,
  book_id text not null,
  word_id bigint not null,
  word_rank integer not null,
  study_count integer not null default 1,
  first_studied_at timestamp with time zone not null default now(),
  last_studied_at timestamp with time zone not null default now(),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint user_word_study_records_pkey primary key (id),
  constraint user_word_study_records_user_fk foreign key (user_id)
    references public."User" (id) on delete cascade,
  constraint user_word_study_records_book_fk foreign key (book_id)
    references public.books (book_id) on delete cascade,
  constraint user_word_study_records_word_fk foreign key (word_id)
    references public.words (id) on delete cascade,
  constraint user_word_study_records_unique unique (user_id, book_id, word_id),
  constraint user_word_study_records_count_check check (study_count > 0)
);

create index if not exists user_word_study_records_user_book_rank_idx
on public.user_word_study_records using btree (user_id, book_id, word_rank);

create index if not exists user_word_study_records_user_recent_idx
on public.user_word_study_records using btree (user_id, last_studied_at desc);
